<a href="https://colab.research.google.com/github/shovo896/TensorFlow/blob/main/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tensor1=tf.veriable([3,4])
print("The shape of a variable:",tensor1.shape)
print("The number of dimensions in the variable:",tf.rank(tensor1).numpy())
print("The size of the tensorflow variable:",tf.size(tensor1).numpy())
print("The variable of the tensorflow variable is :",tensor1.dtype)


AttributeError: module 'tensorflow' has no attribute 'veriable'

In [2]:
# import packages
import tensorflow as tf

# create variable
tensor1 = tf.Variable([3, 4])

# The shape of the variable
print("The shape of the variable: ",
      tensor1.shape)

# The number of dimensions in the variable
print("The number of dimensions in the variable:",
      tf.rank(tensor1).numpy())

# The size of the variable
print("The size of the tensorflow variable:",
      tf.size(tensor1).numpy())

# checking the datatype of the variable
print("The datatype of the tensorflow variable is:",
      tensor1.dtype)

The shape of the variable:  (2,)
The number of dimensions in the variable: 1
The size of the tensorflow variable: 2
The datatype of the tensorflow variable is: <dtype: 'int32'>


In [3]:
import tensorflow as tf
tensor1[1].assign(5)
tensor1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 5], dtype=int32)>

In [4]:
import tensorflow as tf
tensor1=tf.Variable([3,4])
tensor1.assign_add([1,1])
tensor1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [ ]:
Syntax: assign_sub(  delta, use_locking=False, name=None, read_value=True)


parameters:


delta: The value to be subtracted from the variable
use_locking: During the operation, if True, utilise locking.
name: name of the operation.
read_value: If True, anything that evaluates to the modified value of the variable will be returned; if False, the assign op will be returned.



In [6]:
import tensorflow as tf
tensor1=tf.Variable([3,4])
tensor1.assign_sub([1,1])
tensor1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [7]:
import tensorflow as tf
tensor1=tf.Variable([[1,2,3,4]])
tf.reshape(tensor1,shape=(2,2))
tensor1

<tf.Variable 'Variable:0' shape=(1, 4) dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [8]:
import tensorflow as tf
tensor=tf.Variable([1,2,3,2],dtype=float)
tensor1

<tf.Variable 'Variable:0' shape=(1, 4) dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [9]:
import tensorflow as tf
tensor1=tf.Variable([3,4])
tensor2=tf.Variable([5,6])
print("Addition of tensors:",tensor1+tensor2)
print("Subtraction of tensors:",tensor1-tensor2)
print("Multiplication of tensors:",tensor1*tensor2)
print("Division of tensors:",tensor1/tensor2)

Addition of tensors: tf.Tensor([ 8 10], shape=(2,), dtype=int32)
Subtraction of tensors: tf.Tensor([-2 -2], shape=(2,), dtype=int32)
Multiplication of tensors: tf.Tensor([15 24], shape=(2,), dtype=int32)
Division of tensors: tf.Tensor([0.6        0.66666667], shape=(2,), dtype=float64)


broadcasting

In [10]:
import tensorflow as tf
tensor1=tf.Variable([3,4])
tensor2=tf.Variable([2])
output=tensor1*tensor2
print(output)

tf.Tensor([6 8], shape=(2,), dtype=int32)


In [11]:
import tensorflow as tf
tensor1=tf.Variable([3,4])
print('The type of hradware variable used:',+tensor1.device)

TypeError: bad operand type for unary +: 'str'

In [12]:
import tensorflow as tf

# create a variable
tensor1 = tf.Variable([3, 4])

print('The type of hardware variable used : '+tensor1.device)

The type of hardware variable used : /job:localhost/replica:0/task:0/device:CPU:0
