<a href="https://colab.research.google.com/github/shovo896/TensorFlow/blob/main/broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
tensor_2d=tf.constant([[1,2,3],
                       [4,4,5],
                       [7,8,8]])
tensor_2d

NameError: name 'tf' is not defined

Diferent shapes

In [ ]:
import tensorflow as tf
T1=tf.constant([[1,2,3],
                [4,5,6]])
T2=tf.constant([[7,8,10]])
T1
T3=T1+T2
print(T3)

tf.Tensor(
[[ 8 10 13]
 [11 13 16]], shape=(2, 3), dtype=int32)


Different ranks

In [ ]:
import tensorflow as tf
T1=tf.constant([[1,2,3],
                [4,5,6]])
T2=tf.constant([[7,8,10],
                [11,12,13]])
T3=T1+T2
print(T3)

tf.Tensor(
[[ 8 10 13]
 [15 17 19]], shape=(2, 3), dtype=int32)


One of the tensor rank

In [ ]:
import tensorflow as tf
T1=tf.constant([[1,2,3],
                [4,5,6]])
T2=tf.constant([[7,8,10]])
T3=T1+T2
print(T3)

tf.Tensor(
[[ 8 10 13]
 [11 13 16]], shape=(2, 3), dtype=int32)


resulting rank tensor and elementwise operation

SyntaxError: invalid syntax. Perhaps you forgot a comma? (ipython-input-2844994801.py, line 5)

In [ ]:
import tensorflow as tf

# tensor T1
T1 =tf. constant([[[10, 11],   #Rank 3 and shape(2,3,2)
                   [20, 20],
                   [30, 30]],

                 [ [40, 41],
                   [50, 50],
                   [60, 60]   ]])

# tensor T2
T2= tf.constant([[1, 2, 3],    # Rank 2 and shape (2,3)
                 [4, 5, 6]])

#Adding new axis to T2 by .expand_dims() at its trailing end
broadcasted_T2 = tf.expand_dims(T2, axis=-1)

# arithmetic operation
T3=broadcasted_T2+ T1
print(T3)

tf.Tensor(
[[[11 12]
  [22 22]
  [33 33]]

 [[44 45]
  [55 55]
  [66 66]]], shape=(2, 3, 2), dtype=int32)
