<a href="https://colab.research.google.com/github/shovo896/TensorFlow/blob/main/Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Slicing in TensorFlow lets you grab specific sections of your data, just like picking out a slice of cake! It's useful for extracting smaller vectors, matrices, or even higher-dimensional chunks from your tensors.

In [1]:
import tensorflow as tf
t1=tf.constant([1,2,3,4,5,6,7,8,9,10])
t1

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [2]:
s1=tf.slice(t1,begin=[1],size=[3])
print(s1)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [8]:
s1 = t1[1:4]

Beyond single dimension

In [9]:
t2=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
t2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

Slice using tf slice

In [11]:
first_row=tf.slice(t2,[0,0],[1,tf.shape(t2)[1]])
print('First Row:\n,first_row')
second_column=tf.slice(t2,[0,1],[tf.shape(t2)[0],1])
print('\n second column :\n',second_column)


First Row:
,first_row

 second column :
 tf.Tensor(
[[2]
 [5]
 [8]], shape=(3, 1), dtype=int32)


In [12]:
# Get the first row
print('First Row:\n', t2[0])

# Get the second column
print('\nSecond columns:\n', t2[:, 1])

# Get the second and third columns
print('\nSecond & Third columns:\n', t2[:, 1:3])

First Row:
 tf.Tensor([1 2 3], shape=(3,), dtype=int32)

Second columns:
 tf.Tensor([2 5 8], shape=(3,), dtype=int32)

Second & Third columns:
 tf.Tensor(
[[2 3]
 [5 6]
 [8 9]], shape=(3, 2), dtype=int32)


Extracting tensors

In [14]:
import tensorflow as tf
t1=tf.constant([1,2,3,4,5,6,7,8,9,10])
t1


<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [17]:
favorites = tf.gather(t1, indices=[0, 3, 6])
print(favorites)  # Output: [0 3 6]

tf.Tensor([1 4 7], shape=(3,), dtype=int32)


Beyond flat lands

In [18]:
Indices=tf.constant([1,0])
r=tf.gather(t2,indices=Indices)
print('Along row\n',r)

c=tf.gather(t2,indices=Indices,axis=1)
print('\nAlong column\n',c)

Along row
 tf.Tensor(
[[4 5 6]
 [1 2 3]], shape=(2, 3), dtype=int32)

Along column
 tf.Tensor(
[[2 1]
 [5 4]
 [8 7]], shape=(3, 2), dtype=int32)


In [19]:
t3 = tf.constant([[[1, 3, 5, 7],
                   [9, 11, 13, 15]],
                  [[17, 19, 21, 23],
                   [25, 27, 29, 31]]])
t3

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]],

       [[17, 19, 21, 23],
        [25, 27, 29, 31]]], dtype=int32)>

In [20]:
import tensorflow as tf
t4=tf.zeros_like(tf.constant([0,0,0,0,0,0,0,0,0]))
t4

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>

In [21]:
Index=[[1],[3],[6]]
Values=[10,20,30]
t4=tf.scatter_nd(
    indices=Index,
    updates=Values,
    shape=[8]
)
print(t4)

tf.Tensor([ 0 10  0 20  0  0 30  0], shape=(8,), dtype=int32)


Beyond Flat Land

In [22]:
t5=tf.zeros(shape=(4,5))
t5

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

plant seeds

In [23]:
Index = [[0, 0],
         [1, 1],
         [2, 2]]
values = [100, 200, 300]
t5 = tf.scatter_nd(indices=Index,
                   updates=values,
                   shape=t5.shape)
print(t5)  # Output: [[100 0 0 0 0], [0 200 0 0 0], [0 0 300 0 0], [0 0 0 0 0]]

tf.Tensor(
[[100   0   0   0   0]
 [  0 200   0   0   0]
 [  0   0 300   0   0]
 [  0   0   0   0   0]], shape=(4, 5), dtype=int32)
