<a href="https://colab.research.google.com/github/shovo896/TensorFlow/blob/main/manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
values=tf.constant([41,30],dtype=tf.int32)
indices=tf.constant([[1,2],[3,3]],dtype=tf.int64)
sparse_tensor=tf.SparseTensor(indices=indices,values=values,dense_shape=dense_shape)
print(sparse_tensor)


NameError: name 'dense_shape' is not defined

In [2]:
import tensorflow as tf


values = tf.constant([41, 30], dtype=tf.int32)
indices = tf.constant([[1, 2], [3, 3]], dtype=tf.int64)
dense_shape = tf.constant([4, 8], dtype=tf.int64)


sparse_tensor = tf.sparse.SparseTensor(indices=indices, values=values, dense_shape=dense_shape)


print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[1 2]
 [3 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([41 30], shape=(2,), dtype=int32), dense_shape=tf.Tensor([4 8], shape=(2,), dtype=int64))


In [3]:
import tensorflow as tf
desnse_tensor=tf.constant([[1,0,0],[0,0,2],[0,3,0]])
sparse_tensor=tf.sparse.from_dense(dense_tensor)
print(&quot;Dense Tensor:&quot;)
print(desnse_tensor)
print(&quot\n;Sparse Tensor:&quot;)
print(sparse_tensor)

SyntaxError: invalid syntax (ipython-input-2391429741.py, line 4)

In [4]:
import tensorflow as tf


dense_tensor = tf.constant([[1, 0, 0], [0, 0, 2], [0, 3, 0]], dtype=tf.float32)


sparse_tensor = tf.sparse.from_dense(dense_tensor)


print(&quot;Dense Tensor:&quot;)
print(dense_tensor)

print(&quot;\nSparse Tensor:&quot;)
print(sparse_tensor)

SyntaxError: invalid syntax (ipython-input-1258771357.py, line 10)