<a href="https://colab.research.google.com/github/shovo896/TensorFlow/blob/main/manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
values=tf.constant([41,30],dtype=tf.int32)
indices=tf.constant([[1,2],[3,3]],dtype=tf.int64)
sparse_tensor=tf.SparseTensor(indices=indices,values=values,dense_shape=dense_shape)
print(sparse_tensor)


NameError: name 'dense_shape' is not defined

In [2]:
import tensorflow as tf


values = tf.constant([41, 30], dtype=tf.int32)
indices = tf.constant([[1, 2], [3, 3]], dtype=tf.int64)
dense_shape = tf.constant([4, 8], dtype=tf.int64)


sparse_tensor = tf.sparse.SparseTensor(indices=indices, values=values, dense_shape=dense_shape)


print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[1 2]
 [3 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([41 30], shape=(2,), dtype=int32), dense_shape=tf.Tensor([4 8], shape=(2,), dtype=int64))


In [3]:
import tensorflow as tf
desnse_tensor=tf.constant([[1,0,0],[0,0,2],[0,3,0]])
sparse_tensor=tf.sparse.from_dense(dense_tensor)
print(&quot;Dense Tensor:&quot;)
print(desnse_tensor)
print(&quot\n;Sparse Tensor:&quot;)
print(sparse_tensor)

SyntaxError: invalid syntax (ipython-input-2391429741.py, line 4)

In [4]:
import tensorflow as tf


dense_tensor = tf.constant([[1, 0, 0], [0, 0, 2], [0, 3, 0]], dtype=tf.float32)


sparse_tensor = tf.sparse.from_dense(dense_tensor)


print(&quot;Dense Tensor:&quot;)
print(dense_tensor)

print(&quot;\nSparse Tensor:&quot;)
print(sparse_tensor)

SyntaxError: invalid syntax (ipython-input-1258771357.py, line 10)

In [5]:
import tensorflow as tf
sparse_tensor=tf.sparse.SparseTensor(indices=[[0,0],[2,4],values=[10,40],dense_shape=[5,5]])
sparse_tensor=tf.sparse.SparseTensor(indices=[[0,0],[4,2],values=[30,40],dense_shape=[5,5])
result_sparse_tensor=tf.sparse.add(sparse_tensor1,sparse_tensor2)
print(result_sparse_tensor)

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (ipython-input-3519679510.py, line 3)

arithmetic manipulations

In [6]:
import tensorflow as tf

# Create two sparse tensors
sparse_tensor1 = tf.sparse.SparseTensor(indices=[[0, 3], [2, 4]],
                      values=[10, 20],
                      dense_shape=[5, 5])
sparse_tensor2 = tf.sparse.SparseTensor(indices=[[1, 2], [4, 2]],
                      values=[30, 40],
                      dense_shape=[5, 5])

# Add sparse tensors
result_sparse_tensor = tf.sparse.add(sparse_tensor1, sparse_tensor2)

# Print the result
print(result_sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 3]
 [1 2]
 [2 4]
 [4 2]], shape=(4, 2), dtype=int64), values=tf.Tensor([10 30 20 40], shape=(4,), dtype=int32), dense_shape=tf.Tensor([5 5], shape=(2,), dtype=int64))


saprse-dense matrix maltiplication

In [7]:
import tensorflow as tf
sparse_indices=tf.constant([[0,2],[1,0],[1,2],[2,1]],dtype=tf.int64)
sparse_values=tf.constant([1,3,2,4],dtype=tf.int64)

sparse_tensor=tf.sparse.SparseTensor(indices=sparse_indices,values=sparse_values,dense_shape=sparse_shape)
dense_matrix=tf.constant([[1,2,2],[4,5,0],[7,8,0],dtype=tf.float32])

result_dense_matrix=tf.sparse.sparse_dense_matmul(sparse_tensor,dense_matrix)

print(&quot;Sparse Tensor:&quot;)
print(sparse_tensor)
print(&quot;\nDense Matrix:&quot;)
print(dense_matrix)
print(&quot;\nResult Dense Matrix:&quot;)
print(result_dense_matrix)


SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (ipython-input-2865462205.py, line 6)

In [8]:
import tensorflow as tf

# Define a sparse tensor
sparse_indices = tf.constant([[0, 2], [1, 0], [1, 2], [2, 1]], dtype=tf.int64)
sparse_values = tf.constant([1.0, 2.0, 3.0, 4.0], dtype=tf.float32)
sparse_shape = tf.constant([3, 3], dtype=tf.int64)

sparse_tensor = tf.sparse.SparseTensor(indices=sparse_indices, values=sparse_values, dense_shape=sparse_shape)

# Define a dense matrix
dense_matrix = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]], dtype=tf.float32)

# Perform sparse-dense matrix multiplication
result_dense_matrix = tf.sparse.sparse_dense_matmul(sparse_tensor, dense_matrix)

# Print the result
print(&quot;Sparse Tensor:&quot;)
print(sparse_tensor)

print(&quot;\nDense Matrix:&quot;)
print(dense_matrix)

print(&quot;\nResult of Sparse-Dense Matrix Multiplication:&quot;)
print(result_dense_matrix)

SyntaxError: invalid syntax (ipython-input-1992932331.py, line 17)

In [9]:
import tensorflow as tf

# Define a sparse tensor
sparse_indices = tf.constant([[0, 2], [1, 0], [1, 2], [2, 1]], dtype=tf.int64)
sparse_values = tf.constant([1.0, 2.0, 3.0, 4.0], dtype=tf.float32)
sparse_shape = tf.constant([3, 3], dtype=tf.int64)

sparse_tensor = tf.sparse.SparseTensor(indices=sparse_indices, values=sparse_values, dense_shape=sparse_shape)

# Define a dense matrix
dense_matrix = tf.constant([[1.0, 2.0, 3.0],
                            [4.0, 5.0, 6.0],
                            [7.0, 8.0, 9.0]], dtype=tf.float32)

# Perform sparse-dense matrix multiplication
result_dense_matrix = tf.sparse.sparse_dense_matmul(sparse_tensor, dense_matrix)

# Print the result
print("Sparse Tensor:")
print(sparse_tensor)

print("\nDense Matrix:")
print(dense_matrix)

print("\nResult of Sparse-Dense Matrix Multiplication:")
print(result_dense_matrix)


Sparse Tensor:
SparseTensor(indices=tf.Tensor(
[[0 2]
 [1 0]
 [1 2]
 [2 1]], shape=(4, 2), dtype=int64), values=tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))

Dense Matrix:
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)

Result of Sparse-Dense Matrix Multiplication:
tf.Tensor(
[[ 7.  8.  9.]
 [23. 28. 33.]
 [16. 20. 24.]], shape=(3, 3), dtype=float32)


In order to concatenate two sparse tensors, you can use tf.sparse.concat method. Check the example given below that concatenates two sparse tensors.






In [10]:
import tensorflow as tf
sparse_indices1=tf.constant([[0,1],[1,0],[2,2]],dtype=tf.int64)
sparse_values1=tf.constant([1,2,3],dtype=tf.int64)
sparse_shape1=tf.constant([3,3],dtype=tf.int64)

sparse_tensor1=tf.sparse.SparseTensor(indices=sparse_indices1,values=sparse_values1,dense_shape=sparse_shape1)

sparse_indices2=tf.constant([[3,0],[4,0]],dtype=tf.int64)
sparse_values2=tf.constant([6,8],dtype=tf.int32)
sparse_shape2=tf.constant([5,3],dtype=tf.int64)
sparse_tensor=tf.sparse.SparseTensor(indices=sparse_indices2,values=sparse_values2,dense_shape=sparse_shape2)

result_sparse_tensor=tf.shape.concat(axis=0,sp_inputs=[sparse_tensor1,sparse_tensor2])


result_sparse_tensor=tf.sparse.concat(axis=0,sp_inputs=[sparse_tensor1,sparse_tensor2])

print(&quot;Sparse Tensor 1:&quot;)
print(sparse_tensor1)
print(&quot;\nSparse Tensor 2:&quot;)
print(sparse_tensor2)

print(&quot;\nResult of Concatenation:&quot;)
print(result_sparse_tensor)


SyntaxError: invalid syntax (ipython-input-2158506642.py, line 18)

In [11]:
import tensorflow as tf


sparse_indices1 = tf.constant([[0, 1], [1, 0], [2, 2]], dtype=tf.int64)
sparse_values1 = tf.constant([9, 2, 5], dtype=tf.int32)
sparse_shape1 = tf.constant([3, 3], dtype=tf.int64)

sparse_tensor1 = tf.sparse.SparseTensor(indices=sparse_indices1, values=sparse_values1, dense_shape=sparse_shape1)

sparse_indices2 = tf.constant([[3, 1], [4, 0]], dtype=tf.int64)
sparse_values2 = tf.constant([6, 8], dtype=tf.int32)
sparse_shape2 = tf.constant([5, 3], dtype=tf.int64)

sparse_tensor2 = tf.sparse.SparseTensor(indices=sparse_indices2, values=sparse_values2, dense_shape=sparse_shape2)


result_sparse_tensor = tf.sparse.concat(axis=0, sp_inputs=[sparse_tensor1, sparse_tensor2])


print(&quot;Sparse Tensor 1:&quot;)
print(sparse_tensor1)

print(&quot;\nSparse Tensor 2:&quot;)
print(sparse_tensor2)

print(&quot;\nResult of Concatenation:&quot;)
print(result_sparse_tensor)

SyntaxError: invalid syntax (ipython-input-928393757.py, line 20)

In [12]:
import tensorflow as tf


sparse_indices1 = tf.constant([[0, 1], [1, 0], [2, 2]], dtype=tf.int64)
sparse_values1 = tf.constant([9, 2, 5], dtype=tf.int32)
sparse_shape1 = tf.constant([3, 3], dtype=tf.int64)

sparse_tensor1 = tf.sparse.SparseTensor(
    indices=sparse_indices1,
    values=sparse_values1,
    dense_shape=sparse_shape1
)

sparse_indices2 = tf.constant([[3, 1], [4, 0]], dtype=tf.int64)
sparse_values2 = tf.constant([6, 8], dtype=tf.int32)
sparse_shape2 = tf.constant([5, 3], dtype=tf.int64)

sparse_tensor2 = tf.sparse.SparseTensor(
    indices=sparse_indices2,
    values=sparse_values2,
    dense_shape=sparse_shape2
)


result_sparse_tensor = tf.sparse.concat(axis=0, sp_inputs=[sparse_tensor1, sparse_tensor2])

print("Sparse Tensor 1:")
print(sparse_tensor1)

print("\nSparse Tensor 2:")
print(sparse_tensor2)

print("\nResult of Concatenation (Sparse Form):")
print(result_sparse_tensor)


print("\nResult of Concatenation (Dense Form):")
print(tf.sparse.to_dense(result_sparse_tensor))


Sparse Tensor 1:
SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 2]], shape=(3, 2), dtype=int64), values=tf.Tensor([9 2 5], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))

Sparse Tensor 2:
SparseTensor(indices=tf.Tensor(
[[3 1]
 [4 0]], shape=(2, 2), dtype=int64), values=tf.Tensor([6 8], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 3], shape=(2,), dtype=int64))

Result of Concatenation (Sparse Form):
SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 2]
 [6 1]
 [7 0]], shape=(5, 2), dtype=int64), values=tf.Tensor([9 2 5 6 8], shape=(5,), dtype=int32), dense_shape=tf.Tensor([8 3], shape=(2,), dtype=int64))

Result of Concatenation (Dense Form):
tf.Tensor(
[[0 9 0]
 [2 0 0]
 [0 0 5]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 6 0]
 [8 0 0]], shape=(8, 3), dtype=int32)


In [ ]:
import tensorflow as tf
sparse_indices=tf.constant([0,1],[1,0],[2,2],[2,3],dtype=tf.int64)
sparse_values=tf.constant([1,2,3,4],dtype=tf.int32)
sparse_shape=tf.constant([3,4],dtype=tf.int64)
sparse_tensor=tf.sparse.SparseTensor(indices=sparse_indices,values=sparse_values,dense_shape=sparse_shape)
