<a href="https://colab.research.google.com/github/shovo896/TensorFlow/blob/main/shape_reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

tensor shape meauuu

In [1]:
t1-tf.constant([[11,7,8],
                [11,4,0]])
print('Tensor:\n',t1)
print('\nShape of Tensor:',tf.shape(t1).numpy())

NameError: name 't1' is not defined

In [2]:
t1 = tf.constant([[9, 7, 8],
                  [11, 4, 0]])
print('Tensor :\n', t1)
print('\nShape of Tensor:', tf.shape(t1).numpy())

NameError: name 'tf' is not defined

In [3]:
import tensorflow as tf

t1 = tf.constant([[9, 7, 8],
                  [11, 4, 0]])

print('Tensor:\n', t1.numpy())
print('\nShape of Tensor:', t1.shape)


Tensor:
 [[ 9  7  8]
 [11  4  0]]

Shape of Tensor: (2, 3)


reshapin

In [4]:
t2=tf.reshape(t1,[6])
print('Tensor:\n',t2)
print('\nShape of tensor:',tf.shape(t2).numpy())

Tensor:
 tf.Tensor([ 9  7  8 11  4  0], shape=(6,), dtype=int32)

Shape of tensor: [6]


Reshaping 2d vector

In [5]:
t3=tf.reshape(t2,[1,6])
print('Tensor\n',t3)
print('\nShape of Tensor:',tf.shape(t3).numpy())

Tensor
 tf.Tensor([[ 9  7  8 11  4  0]], shape=(1, 6), dtype=int32)

Shape of Tensor: [1 6]


We use permuted dimensions to control the arrangement of dimensions in the output tensor, allowing for flexibility in tensor transformations such as transposition.

The original tensor t is defined as a 2D tensor with two rows and three columns, represented as a Python list of lists.
Reshaping the tensor using tf.reshape() rearranges its elements to match a specified shape, resulting in a 3x2 tensor.
Transposing the tensor with tf.transpose() changes the arrangement of dimensions. Here, the perm argument [1, 0] indicates that the rows and columns should be swapped, resulting in a transposed tensor.
The reshaped and transposed tensors are converted to NumPy arrays using .numpy() for ease of printing and handling.