<a href="https://colab.research.google.com/github/shovo896/TensorFlow/blob/main/tensorflow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tensor = tf.constant([1,2,3],[4,5,6])
shape=tensor.shape
print('Tensor:',tensor)
print('Tensor shape',shape)

TypeError: Cannot convert the argument `type_value`: [4, 5, 6] to a TensorFlow DType.

In [2]:
import tensorflow as tf

# Create a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Get the shape of the tensor
shape = tensor.shape

print('Tensor: ', tensor)
print('Tensor shape: ', shape)

Tensor:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor shape:  (2, 3)


In [3]:
import tensorflow as tf
tensor=tf.constant([[1,2,3],[4,5,6]])
size=tf.size(tensor)
print('Tensor:',tensor)
print('Tensor size:',size)


Tensor: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor size: tf.Tensor(6, shape=(), dtype=int32)


In [6]:
import tensorflow as tf
scalar=tf.constant(5)
vector=tf.constant([1,2,3])
matrix=tf.constant([1,2],[4,5])
tensor_3d=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])

#get the rank of all tensors
rank_scalar=tf.rank(scalar)
rank_vector=tf.rank(vector)
rank_matrix=tf.rank(matrix)
rank_tensor_3d=tf.rank(tensor_3d)

print('Rank of scalar:',rank_scalar)
print('Rank of vector:',rank_vector)
print('Rank of matrix:',rank_matrix)
print('Rank of tensor_3d:',rank_tensor_3d)

TypeError: Cannot convert the argument `type_value`: [4, 5] to a TensorFlow DType.

In [7]:
import tensorflow as tf

# Create tensors of different ranks
scalar = tf.constant(5)  # Rank 0 tensor (scalar)
vector = tf.constant([1, 2, 3])  # Rank 1 tensor (vector)
matrix = tf.constant([[1, 2], [3, 4]])  # Rank 2 tensor (matrix)
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Rank 3 tensor (3D)

# Get the rank of tensors
rank_scalar = tf.rank(scalar)
rank_vector = tf.rank(vector)
rank_matrix = tf.rank(matrix)
rank_3d = tf.rank(tensor_3d)

print('Rank of scalar:', rank_scalar.numpy())
print('Rank of vector:', rank_vector.numpy())
print('Rank of matrix:', rank_matrix.numpy())
print('Rank of 3D tensor:', rank_3d.numpy())

Rank of scalar: 0
Rank of vector: 1
Rank of matrix: 2
Rank of 3D tensor: 3


Tensor dimension refers to the length along a particular axis of a tensor. In simpler terms, it is the size or extent of a tensor along a specific direction. Each axis of a tensor corresponds to a dimension, and the number of dimensions in a tensor is its rank.



In [8]:
import tensorflow as tf
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
shape = tensor.shape

# Get the length of the first dimension
dim1_length = shape[0]

# Get the length of the second dimension
dim2_length = shape[1]

print('Tensor shape:', shape)
print('Length of first dimension:', dim1_length)
print('Length of second dimension:', dim2_length)

Tensor shape: (2, 3)
Length of first dimension: 2
Length of second dimension: 3
