<a href="https://colab.research.google.com/github/shovo896/TensorFlow/blob/main/transform.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
t=tf.constant([[1,2,3],[4,5,6]])
print('Orginal tensor')
print(t)
#Reshaping into 3x2 tensor
reshaped_tensor=tf.reshape(t,[3,2])
print("\nReshaped tensor")
#Transposing with permuted dimehsions
transposed_tensor=tf.transpose(t,perm=[1,0])
print("\nTransposed tensor")
print(transposed_tensor)

Orginal tensor
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Reshaped tensor

Transposed tensor
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


using the special value -1 as shape

In [2]:
t=tf.constant([[1,2,3],[4,5,6]])
result=tf.reshape(t,[-1])
print('Flattened tensor:\n',result)
print('\n Orginal Tensor shape:',tf.shape(t))
print('\nFlattened tensor shape:',tf.shape(result))

Flattened tensor:
 tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)

 Orginal Tensor shape: tf.Tensor([2 3], shape=(2,), dtype=int32)

Flattened tensor shape: tf.Tensor([6], shape=(1,), dtype=int32)
